# nginx proxy address -

name: memcached
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  server:
    image: 'bitnami/memcached:latest'
    container_name: memcached
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      - TZ=${TZ:-America/New_York}
      - MEMCACHED_CACHE_SIZE=1024
      - MEMCACHED_MAX_CONNECTIONS=2000
      - MEMCACHED_USERNAME=${DB_ADMIN_NAME:-root}
      - MEMCACHED_PASSWORD=${DB_ADMIN_PASS:-MpK91fH07ZVER8zINXrEPBHzfcRUu1fc}
    extra_hosts:
      - 'localhost:172.17.0.1'
      - 'memcached:host-gateway'
      - 'host.docker.internal:host-gateway'
    networks:
      - memcached

networks:
  memcached:
    name: memcached
    external: false
